
name: Build Linux ARM64

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set environment variables
        run: |
          echo "GOARCH=arm64" >> $GITHUB_ENV
          echo "GOOS=linux" >> $GITHUB_ENV
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="v0.0.0-${GITHUB_SHA::8}"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "ARCH_NAME=aarch64" >> $GITHUB_ENV
          
      - name: Build for ARM64
        env:
          DOCKER_BUILDKIT: 1
        run: |
          # BuildKit 활성화 및 새 빌더 생성
          docker buildx create --use --name arm64-builder --platform linux/arm64
          docker buildx inspect --bootstrap

          # ARM64용 이미지 빌드
          docker buildx build --platform linux/arm64 --load --tag minitia/minitiad-shared:arm64 . -f Dockerfile.arm64

          # ARM64 이미지를 사용하여 빌드 결과물 추출
          mkdir -p ./build
          docker create --name temp minitia/minitiad-shared:arm64
          docker cp temp:/usr/local/bin/minitiad ./build/
          docker cp temp:/lib/libwasmvm.so ./build/
          docker rm temp

          # 결과물 패키징
          cd ./build
          mkdir -p miniwasm_${VERSION}
          mv minitiad miniwasm_${VERSION}/
          mv libwasmvm.so miniwasm_${VERSION}/libwasmvm.${ARCH_NAME}.so
          tar -czvf miniwasm_${VERSION}_Linux_${ARCH_NAME}.tar.gz miniwasm_${VERSION}
          mv miniwasm_${VERSION}_Linux_${ARCH_NAME}.tar.gz ../

          # 빌드 결과 확인
          cd ..
          ls -l
          file miniwasm_${VERSION}_Linux_${ARCH_NAME}.tar.gz

          # 빌더 제거
          docker buildx rm arm64-builder

      - name: List files
        run: ls -l
        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
              ./miniwasm_${{ env.VERSION }}_Linux_${{ env.ARCH_NAME }}.tar.gz
